:_repeat0 = :a
if (:_repeat0 > 0) [
forward10

]
if (:_repeat0 > 1) [
forward10

]
if (:_repeat0 > 2) [
forward10

]
if (:_repeat0 > 3) [
forward10

]
if (:_repeat0 > 4) [
forward10

]
if (:_repeat0 > 5) [
forward10

]
if (:_repeat0 > 6) [
forward10

]
if (:_repeat0 > 7) [
forward10

]
if (:_repeat0 > 8) [
forward10

]
if (:_repeat0 > 9) [
forward10

]
if (:_repeat0 > 10) [
forward10

]
if (:_repeat0 > 11) [
forward10

]
if (:_repeat0 > 12) [
forward10

]
if (:_repeat0 > 13) [
forward10

]
if (:_repeat0 > 14) [
forward10

]
if (:_repeat0 > 15) [
forward10

]
if (:_repeat0 > 16) [
forward10

]
if (:_repeat0 > 17) [
forward10

]
if (:_repeat0 > 18) [
forward10

]
if (:_repeat0 > 19) [
forward10

]
if (:_repeat0 > 20) [
forward10

]
if (:_repeat0 > 21) [
forward10

]
if (:_repeat0 > 22) [
forward10

]
if (:_repeat0 > 23) [
forward10

]
if (:_repeat0 > 24) [
forward10

]
if (:_repeat0 > 25) [
forward10

]
if (:_repeat0 > 26) [
forward10

]
if (:_repeat0 > 27) [
forward10

]
if (:_repeat0 > 28) [
forward10

]
if (:_repeat0 > 29) [
forward10

]
if (:_repeat0 > 30) [
forward10

]
if (:_repeat0 > 31) [
forward10

]
if (:_repeat0 > 32) [
forward10

]
if (:_repeat0 > 33) [
forward10

]
if (:_repeat0 > 34) [
forward10

]
if (:_repeat0 > 35) [
forward10

]
if (:_repeat0 > 36) [
forward10

]
if (:_repeat0 > 37) [
forward10

]
if (:_repeat0 > 38) [
forward10

]
if (:_repeat0 > 39) [
forward10

]
if (:_repeat0 > 40) [
forward10

]
if (:_repeat0 > 41) [
forward10

]
if (:_repeat0 > 42) [
forward10

]
if (:_repeat0 > 43) [
forward10

]
if (:_repeat0 > 44) [
forward10

]
if (:_repeat0 > 45) [
forward10

]
if (:_repeat0 > 46) [
forward10

]
if (:_repeat0 > 47) [
forward10

]
if (:_repeat0 > 48) [
forward10

]
if (:_repeat0 > 49) [
forward10

]
if (:_repeat0 > 50) [
forward10

]
if (:_repeat0 > 51) [
forward10

]
if (:_repeat0 > 52) [
forward10

]
if (:_repeat0 > 53) [
forward10

]
if (:_repeat0 > 54) [
forward10

]
if (:_repeat0 > 55) [
forward10

]
if (:_repeat0 > 56) [
forward10

]
if (:_repeat0 > 57) [
forward10

]
if (:_repeat0 > 58) [
forward10

]
if (:_repeat0 > 59) [
forward10

]
if (:_repeat0 > 60) [
forward10

]
if (:_repeat0 > 61) [
forward10

]
if (:_repeat0 > 62) [
forward10

]
if (:_repeat0 > 63) [
forward10

]
if (:_repeat0 > 64) [
forward10

]
if (:_repeat0 > 65) [
forward10

]
if (:_repeat0 > 66) [
forward10

]
if (:_repeat0 > 67) [
forward10

]
if (:_repeat0 > 68) [
forward10

]
if (:_repeat0 > 69) [
forward10

]
if (:_repeat0 > 70) [
forward10

]
if (:_repeat0 > 71) [
forward10

]
if (:_repeat0 > 72) [
forward10

]
if (:_repeat0 > 73) [
forward10

]
if (:_repeat0 > 74) [
forward10

]
if (:_repeat0 > 75) [
forward10

]
if (:_repeat0 > 76) [
forward10

]
if (:_repeat0 > 77) [
forward10

]
if (:_repeat0 > 78) [
forward10

]
if (:_repeat0 > 79) [
forward10

]
if (:_repeat0 > 80) [
forward10

]
if (:_repeat0 > 81) [
forward10

]
if (:_repeat0 > 82) [
forward10

]
if (:_repeat0 > 83) [
forward10

]
if (:_repeat0 > 84) [
forward10

]
if (:_repeat0 > 85) [
forward10

]
if (:_repeat0 > 86) [
forward10

]
if (:_repeat0 > 87) [
forward10

]
if (:_repeat0 > 88) [
forward10

]
if (:_repeat0 > 89) [
forward10

]
if (:_repeat0 > 90) [
forward10

]
if (:_repeat0 > 91) [
forward10

]
if (:_repeat0 > 92) [
forward10

]
if (:_repeat0 > 93) [
forward10

]
if (:_repeat0 > 94) [
forward10

]
if (:_repeat0 > 95) [
forward10

]
if (:_repeat0 > 96) [
forward10

]
if (:_repeat0 > 97) [
forward10

]
if (:_repeat0 > 98) [
forward10

]
if (:_repeat0 > 99) [
forward10

]

assume:a<1
assert:turtleX<=1&&:turtleX>=-1&&:turtleY<=1&&:turtleY>=-1
