forward10
assert:turtleX==10
:_repeat0 = :turtleX
assume :_repeat0 <= 50 
if (:_repeat0 > 0) [
:x=:x+1

]
if (:_repeat0 > 1) [
:x=:x+1

]
if (:_repeat0 > 2) [
:x=:x+1

]
if (:_repeat0 > 3) [
:x=:x+1

]
if (:_repeat0 > 4) [
:x=:x+1

]
if (:_repeat0 > 5) [
:x=:x+1

]
if (:_repeat0 > 6) [
:x=:x+1

]
if (:_repeat0 > 7) [
:x=:x+1

]
if (:_repeat0 > 8) [
:x=:x+1

]
if (:_repeat0 > 9) [
:x=:x+1

]
if (:_repeat0 > 10) [
:x=:x+1

]
if (:_repeat0 > 11) [
:x=:x+1

]
if (:_repeat0 > 12) [
:x=:x+1

]
if (:_repeat0 > 13) [
:x=:x+1

]
if (:_repeat0 > 14) [
:x=:x+1

]
if (:_repeat0 > 15) [
:x=:x+1

]
if (:_repeat0 > 16) [
:x=:x+1

]
if (:_repeat0 > 17) [
:x=:x+1

]
if (:_repeat0 > 18) [
:x=:x+1

]
if (:_repeat0 > 19) [
:x=:x+1

]
if (:_repeat0 > 20) [
:x=:x+1

]
if (:_repeat0 > 21) [
:x=:x+1

]
if (:_repeat0 > 22) [
:x=:x+1

]
if (:_repeat0 > 23) [
:x=:x+1

]
if (:_repeat0 > 24) [
:x=:x+1

]
if (:_repeat0 > 25) [
:x=:x+1

]
if (:_repeat0 > 26) [
:x=:x+1

]
if (:_repeat0 > 27) [
:x=:x+1

]
if (:_repeat0 > 28) [
:x=:x+1

]
if (:_repeat0 > 29) [
:x=:x+1

]
if (:_repeat0 > 30) [
:x=:x+1

]
if (:_repeat0 > 31) [
:x=:x+1

]
if (:_repeat0 > 32) [
:x=:x+1

]
if (:_repeat0 > 33) [
:x=:x+1

]
if (:_repeat0 > 34) [
:x=:x+1

]
if (:_repeat0 > 35) [
:x=:x+1

]
if (:_repeat0 > 36) [
:x=:x+1

]
if (:_repeat0 > 37) [
:x=:x+1

]
if (:_repeat0 > 38) [
:x=:x+1

]
if (:_repeat0 > 39) [
:x=:x+1

]
if (:_repeat0 > 40) [
:x=:x+1

]
if (:_repeat0 > 41) [
:x=:x+1

]
if (:_repeat0 > 42) [
:x=:x+1

]
if (:_repeat0 > 43) [
:x=:x+1

]
if (:_repeat0 > 44) [
:x=:x+1

]
if (:_repeat0 > 45) [
:x=:x+1

]
if (:_repeat0 > 46) [
:x=:x+1

]
if (:_repeat0 > 47) [
:x=:x+1

]
if (:_repeat0 > 48) [
:x=:x+1

]
if (:_repeat0 > 49) [
:x=:x+1

]

assert:x<=100
