:i = 1
:n = 10
repeat :n[
    penup
    forward 40
    right 90
    forward 40
    pendown
    forward :i*15
    :i = :i +1
    penup
    forward 40
    right 90
    forward 40
    pendown
    forward :i*15
    :i = :i +1
    penup
    forward 40
    right 90
    forward 40
    pendown
    forward :i*15
    :i = :i +1
    penup
    forward 40
    right 90
    forward 40
    pendown
    forward :i*15
    :i = 1
]